# Generated by Django 3.1.3 on 2021-07-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotification',
            name='notification_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
