# Generated by Django 3.0.8 on 2021-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210618_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/static/prof_image'),
        ),
    ]
