# Generated by Django 3.0.8 on 2021-06-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210618_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prof_cover',
            field=models.ImageField(blank=True, null=True, upload_to='prof_cover'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to='prof_image'),
        ),
    ]
