# Generated by Django 3.1.3 on 2021-06-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0017_auto_20210625_0942'),
        ('accounts', '0010_usernotification_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
    ]
