# Generated by Django 3.1.3 on 2021-06-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20210621_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
