# Generated by Django 3.1.3 on 2021-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20210621_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
