# Generated by Django 3.1.3 on 2021-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20210621_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='twt_time',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
