# Generated by Django 3.1.3 on 2021-06-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_comment_twt_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='twt_time',
            new_name='cmd_time',
        ),
    ]
