# Generated by Django 3.1.3 on 2021-06-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20210622_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cmd_time',
            new_name='comment_time',
        ),
    ]
