# Generated by Django 3.1.3 on 2021-06-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20210622_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='twt_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
