# Generated by Django 3.1.3 on 2021-06-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_auto_20210622_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetLike',
        ),
    ]
