# Generated by Django 3.1.3 on 2021-06-24 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0015_auto_20210622_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='_tweet_comments_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
