# Generated by Django 3.1.3 on 2021-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0016_tweet_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='comments',
        ),
        migrations.AddField(
            model_name='tweet',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
